version: '3.8'

services:
  frontend:
    image: krccr.ccs.tencentyun.com/coin/open_canvas:laster
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./app-data:/app/data